[package]
name = "miner"
version = "0.1.0"
authors = ["Tim Boldt <tim.boldt@gmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.4.0"

[dependencies.rand]
version = "0.8.0"
default-features = false
