[package]
name = "miner"
version = "0.1.0"
authors = ["Tim Boldt <tim.boldt@gmail.com>"]
edition = "2018"

[dependencies]
bracket-lib = "0.8"

[dependencies.rand]
version = "0.8.0"
default-features = false
