[package]
name = "miner"
version = "0.1.0"
authors = ["Tim Boldt <tim.boldt@gmail.com>"]
edition = "2018"

[dependencies.bracket-lib]
version = "0.8"
#default-features = false
#features = [ "crossterm" ]

[dependencies.getrandom]
version = "0.2"
features = [ "js" ]